name: nanop
channels:
  - bioconda
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - biopython
  - nanopolish
  - minimap2
  - pyvcf
  - h5py
  - tqdm
  - plotly  
  - pycoQC
  - pandas
  - samtools
  - bcftools
  - bwa
  - matplotlib
  - openjdk
  - ete3
  - mafft
  - pysam
  - clint
  - vsearch